MusicApp/config/routes.rb
Rails.application.routes.draw do
  resources :bands, only: [:show] do
    resources :albums, only: [:new]
  end
  resources :albums, only: [:show] do
    resources :tracks, only: [:new]
  end
  resource :session, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tracks, only: [:create, :edit, :show, :update, :destroy]
  resources :albums, only: [:create, :edit, :show, :update, :destroy]
  resources :bands
  resources :users #, only: [:create, :new, :show]
end

MusicApp/app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id          :bigint(8)        not null, primary key
#  album_id    :integer          not null
#  title       :string           not null
#  ord         :integer          not null
#  lyrics      :text             not null
#  bonus_track :boolean          default(FALSE), not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Track < ApplicationRecord
  validates_presence_of :title, :ord, :lyrics, :album_id
  after_initialize :default_values

  belongs_to :album

  private

  def default_values
    self.bonus_track ||= false
  end
end

MusicApp/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track, only: [:show, :edit, :update, :destroy]

  # GET /tracks
  # GET /tracks.json
  def index
    @tracks = Track.all
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
  end

  # GET /tracks/new
  def new
    @track = Track.new
  end

  # GET /tracks/1/edit
  def edit
  end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = Track.new(track_params)

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: 'Track was successfully created.' }
        format.json { render :show, status: :created, location: @track }
      else
        format.html { render :new }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracks/1
  # PATCH/PUT /tracks/1.json
  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
        format.json { render :show, status: :ok, location: @track }
      else
        format.html { render :edit }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    @track.destroy
    respond_to do |format|
      format.html { redirect_to tracks_url, notice: 'Track was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track
      @track = Track.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def track_params
      params.require(:track).permit(:album_id, :title, :ord, :lyrics, :bonus_track)
    end
end

MusicApp/app/helpers/tracks_helper.rb
module TracksHelper
end

MusicApp/app/views/tracks/_form.html.erb
<%= form_with(model: track, local: true) do |form| %>
  <% if track.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
      <% track.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :album_id %>
    <%= form.number_field :album_id %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :ord %>
    <%= form.number_field :ord %>
  </div>

  <div class="field">
    <%= form.label :lyrics %>
    <%= form.text_area :lyrics %>
  </div>

  <div class="field">
    <%= form.label :bonus_track %>
    <%= form.check_box :bonus_track %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

MusicApp/app/views/tracks/edit.html.erb
<h1>Editing Track</h1>

<%= render 'form', track: @track %>

<%= link_to 'Show', @track %> |
<%= link_to 'Back', tracks_path %>

MusicApp/app/views/tracks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tracks</h1>

<table>
  <thead>
    <tr>
      <th>Album</th>
      <th>Title</th>
      <th>Ord</th>
      <th>Lyrics</th>
      <th>Bonus track</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tracks.each do |track| %>
      <tr>
        <td><%= track.album_id %></td>
        <td><%= track.title %></td>
        <td><%= track.ord %></td>
        <td><%= track.lyrics %></td>
        <td><%= track.bonus_track %></td>
        <td><%= link_to 'Show', track %></td>
        <td><%= link_to 'Edit', edit_track_path(track) %></td>
        <td><%= link_to 'Destroy', track, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Track', new_track_path %>

MusicApp/app/views/tracks/new.html.erb
<h1>New Track</h1>

<%= render 'form', track: @track %>

<%= link_to 'Back', tracks_path %>

MusicApp/app/views/tracks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Album:</strong>
  <%= @track.album_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @track.title %>
</p>

<p>
  <strong>Ord:</strong>
  <%= @track.ord %>
</p>

<p>
  <strong>Lyrics:</strong>
  <%= @track.lyrics %>
</p>

<p>
  <strong>Bonus track:</strong>
  <%= @track.bonus_track %>
</p>

<%= link_to 'Edit', edit_track_path(@track) %> |
<%= link_to 'Back', tracks_path %>