MusicApp/config/routes.rb
Rails.application.routes.draw do
  resources :bands, only: [:show] do
    resources :albums, only: [:new]
  end
  resources :albums, only: [:show] do
    resources :tracks, only: [:new]
  end
  resource :session, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tracks, only: [:create, :edit, :show, :update, :destroy]
  resources :albums, only: [:create, :edit, :show, :update, :destroy]
  resources :bands
  resources :users #, only: [:create, :new, :show]
end

MusicApp/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint(8)        not null, primary key
#  band_id    :integer          not null
#  title      :string           not null
#  year       :integer          not null
#  live       :boolean          default(FALSE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord
  validates_presence_of :title, :year
  after_initialize :default_values

  belongs_to :band
  has_many :tracks

  private

  def default_values
    self.live ||= false
  end
end

MusicApp/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:band_id, :title, :year, :live)
    end
end

MusicApp/app/helpers/albums_helper.rb
module AlbumsHelper
end

MusicApp/app/views/albums/_form.html.erb
<%= form_with(model: album, local: true) do |form| %>
  <% if album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :band_id %>
    <%= form.number_field :band_id %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>

  <div class="field">
    <%= form.label :live %>
    <%= form.check_box :live %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

MusicApp/app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

MusicApp/app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Albums</h1>

<table>
  <thead>
    <tr>
      <th>Band</th>
      <th>Title</th>
      <th>Year</th>
      <th>Live</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= album.band_id %></td>
        <td><%= album.title %></td>
        <td><%= album.year %></td>
        <td><%= album.live %></td>
        <td><%= link_to 'Show', album %></td>
        <td><%= link_to 'Edit', edit_album_path(album) %></td>
        <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Album', new_album_path %>

MusicApp/app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Back', albums_path %>

MusicApp/app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Band:</strong>
  <%= @album.band_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @album.title %>
</p>

<p>
  <strong>Year:</strong>
  <%= @album.year %>
</p>

<p>
  <strong>Live:</strong>
  <%= @album.live %>
</p>

<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>