MusicApp/config/routes.rb
Rails.application.routes.draw do
  resources :bands, only: [:show] do
    resources :albums, only: [:new]
  end
  resources :albums, only: [:show] do
    resources :tracks, only: [:new]
  end
  resource :session, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tracks, only: [:create, :edit, :show, :update, :destroy]
  resources :albums, only: [:create, :edit, :show, :update, :destroy]
  resources :bands
  resources :users #, only: [:create, :new, :show]
end

MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <% if @current_user %>
      <form action="<%= session_url %>" method="post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="delete">
        <input type="submit" value="Log Out">
      </form>
    <% else %>
      <a href="<%= new_session_url %>"><button>Log In</button></a>
      <a href="<%= new_user_url %>"><button>Sign Up</button></a>
    <% end %>
  </header>
  <body>

      <% if flash[:errors] && flash[:errors][0] %>
        <div id="error_explanation">
          <h2><%= pluralize(flash[:errors].count, "error") %> prohibited this user from being saved:</h2>

          <ul>
          <% flash[:errors].each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% elsif flash[:notices] && flash[:notices][0] %>
        <div id="success_explanation">
          <ul>
          <% flash[:notices].each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

    <%= yield %>
  </body>
</html>